---
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-yaml
        args: ["--unsafe"]
      - id: trailing-whitespace
      - id: detect-private-key
      - id: name-tests-test
        args: ["--pytest-test-first"]
      - id: detect-private-key
      - id: check-merge-conflict
      - id: check-illegal-windows-names
      - id: debug-statements
      - id: end-of-file-fixer
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: "v0.14.11"
    hooks:
      # Run the linter.
      - id: ruff-check
        types_or: [python, pyi]
        args: [--fix]
      # Run the formatter.
      - id: ruff-format
        types_or: [python, pyi]
  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.45.0
    hooks:
      - id: markdownlint
        name: markdownlint on /content/*.md (markdown)
        args: ["--fix"]
        files: ^content/.*\.md$

fail_fast: false
files: ".*"
exclude: |
  (?x)^(
      desktop.ini
  )$
